### ISSUE TITLE
[Feat] 매출 관련 페이지 구현

### ISSUE THREAD

**Issue by jason-gb** [beyond-sw-camp/be08-fin-3Dasoo-SalesBoost-FE#37]
## 📃 기능 설명
> 매출 관련 페이지 구현

<br>

## ✔️ 작업 상세 내용
- [ ] 매출 crud 페이지 구현
- [ ] 라우팅 연결

<br>

**Comment by uzz99** [comment]
이슈 우측에 있는 것들 설정 해주십쇼
